### ISSUE TITLE
Create prototype of client

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/geobroker#4]
- [x] display own position
- [ ] send own position to geobroker
- [x] display units from scope (regular updates)
- [ ] display incidents from scope
- [x] re-use existing markers (e.g. to keep state of popup)
- [ ] encode unit type and status in the marker's appearance
- [ ] create switchable auto-pan mode (follow own position)
- [ ] create log pane for error messages

**Comment by heinrichmartin** [comment]
moved to [geoclient](https://github.com/wrk-fmd/geoclient)
